name: Bug report
about: Report a reproducible bug.
title: '[Bug]: '

body: 
  - type: markdown
    attributes: |
      Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. On discord at Username#42069
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: What is the problem ?
      description: Please tell us more information about this problem.
      placeholder: Describe what you see and why it is a problem.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the problem ?
      description: Please tell us how to reproduce the problem.
      placeholder: Tell us a series of steps to reproduce the problem.
    validations:
      required: true
  - type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false